const actionType={
    "NEW_MOVE":"NEW_MOVE",
    "GENERATE_CANDIDATE_MOVES":"GENERATE_CANDIDATE_MOVES",
    "CLEAR_CANDIDATES":"CLEAR_CANDIDATES ", 
    "PROMOTION_OPEN":"PROMOTION_OPEN",
    "PROMOTION_CLOSE":"PROMOTION_CLOSE"
}

export default actionType